<?php

const H3_ERR_CODE_INVALID_RES = 1;
const H3_ERR_CODE_INVALID_INDEX = 2;
const H3_ERR_CODE_UNSUPPORTED_UNIT = 3;
const H3_ERR_CODE_COMPACT_ERROR = 4;
const H3_ERR_CODE_UNCOMPACT_ERROR = 5;
const H3_ERR_CODE_LINE_SIZE_ERROR = 6;
const H3_ERR_CODE_PENTAGON_ENCOUNTERED = 7;

const H3_AREA_UNIT_KM2 = 0;
const H3_AREA_UNIT_M2 = 1;
const H3_AREA_UNIT_RADS2 = 2;

const H3_LENGTH_UNIT_KM = 0;
const H3_LENGTH_UNIT_M = 1;
const H3_LENGTH_UNIT_RADS = 2;
